server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  queue: "orders.v1.order-created-notification"
  exchange: "orders.v1.order-created"