server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 980250113360d9
    password: b19a4bf1090a47
    properties:
      mail:
        stmp:
          auth: true 
      smpt:
        starttls:
          enable: true

app:
  queue: "orders.v1.order-created-notification"
  exchange: "orders.v1.order-created"