server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        stmp:
          auth: true 
      smpt:
        starttls:
          enable: true

app:
  queue: "orders.v1.order-created-notification"
  exchange: "orders.v1.order-created"