server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: order-service
    password: 123

app:
  exchange:
    fanout: "orders.v1.order-created"
    fanout-dead-letter: "orders.v1.order-created.dl"