server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cashback
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  queue: "orders.v1.order-created-cashback"
  exchange: "orders.v1.order-created"